# Generated by Django 5.0.4 on 2024-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='listened',
        ),
    ]
